### PR TITLE
Annotate getRandomDigitString() with @NonCPS

### PR DESCRIPTION
**Pull request by nre-ableton**
I suspect that the IntRange created by the `(0..length - 1).collect`
statement is causing java.io.NotSerializableException to be thrown if
Jenkins attempts to save build state when this method is being
executed. Unfortunately, it's a bit hard to verify with a high degree
of certainty that this is the cause of such exceptions, but
fortunately we are not calling any pipeline steps from this method so
it is safe to annotate with @NonCPS anyways.

Also unfortunate is the fact that we can't provide a test for this
behavior.

---

ping @AbletonDevTools/gotham-city

### CODE REVIEW

**Comment by ala-ableton** [comment]
@nre-ableton in a29d9c0's commit message, a link to some documentation about `cps`/`NonCPS` would be nice.

**Comment by nre-ableton** [comment]
@ala-ableton Done!

**Comment by ala-ableton** [comment]
@nre-ableton I think we could add a test, which creates an `IntRange`, tries to seriaize it and then expects the exception to be raised.

**Comment by nre-ableton** [comment]
@ala-ableton But serializing the object will in all likelihood succeed anyways. It is Jenkins that is throwing the exception, not the standard Serialization methods. We'd have to exactly replicate how Jenkins serializes objects in order to do this. I have no idea to do and am skeptical of duplicating such a large amount of Java code in our test cases.

But moreover, the `@NonCPS` annotation does not prevent the exception from being thrown, but rather it prevents serialization from being performed on such methods. From the documentation page added to the commit message body:

> However the safest approach is to isolate use of nonserializable state inside a method marked with the annotation `@NonCPS`. Such a method will be treated as “native” by the Pipeline engine, and its local variables never saved.

**Comment by ala-ableton** [comment]
From https://github.com/jenkinsci/pipeline-plugin/blob/master/TUTORIAL.md#serializing-local-variables:
> This occurs because the `matcher` local variable is of a type (`Matcher`) not considered serializable by Java. 

There is nothing Jenkins specific here. That's why I assumed we could write a test that tries to serialize an `IntRange`.

**Comment by nre-ableton** [comment]
The Jenkins-specific bit is that Jenkins (seems to be) serializing its current runtime state -- you can't serialize a method. If we attempt to serialize our own objects, that will always succeed.

We don't need to write a test which attempts to serialize `IntRange` (or anything else for that matter). We could just use reflection to see if a class implements the `Serializable` interface.

We'd be better off writing some type of static check to examine methods *not* annotated with `@NonCPS`, look at all the variables therein, and see if they implement the `Serializable` interface (or are primitives, which are of course serializable). That could be a pretty cool project and potentially useful to the wider Jenkins community, but certainly beyond the scope of this PR. 😄

**Comment by ala-ableton** [comment]
> I suspect that the IntRange created by the `(0..length - 1).collect`
statement is causing java.io.NotSerializableException to be thrown if
Jenkins attempts to save build state when this method is being
executed.

I just want something (a test, an experiment on a wip branch, an experiment in the Jenkins sandbox, ...) to convert "I suspect that" into "yes, serializing `IntRange` doesn't work".

**Comment by nre-ableton** [comment]
@ala-ableton Fair enough; I just ran this pipeline on the *staging* server:

```groovy
node('master') {
    def foo = new IntRange(1,2)
    if (foo instanceof Serializable) {
        echo "it is"
    } else {
        echo "not"
    }
}
```

After approving the security sandbox exemption for `new IntRange(int, int)`, it printed out `not`. Does that satisfy your curiosity? 😄

**Comment by ala-ableton** [comment]
@nre-ableton it does. Please reword the commit message of 83cf18e now.

**Comment by nre-ableton** [comment]
@ala-ableton Done!

**Pull request merged**
